volumes:
  postgres_data:


services:
  db:
    restart: always
    image: postgres:15.0
    container_name: spring_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - envs/.env.local.db

#  adminer:
#    restart: always
#    build: ../adminer-extended
#    ports:
#      - "8086:8080"

  adminer:
    restart: always
    image: dpage/pgadmin4:latest
    ports:
      - "8086:8080"
    environment:
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin